### PR TITLE
Created Static Landing Page

### PR DESCRIPTION
**Pull request by simranquirky**
Screenshot (416)

Created static landing page.

Looking forward to work more on the frontend and integrating it with the backend once I receive enough information about 
- details of the login/signup page
- subsequent actions workflow on each click

### CODE REVIEW

**Comment by Ash515** [comment]
Great Keep Contribute  !

**Comment by Ash515** [comment]
Create an issue for this immediately

**Comment by simranquirky** [comment]
> Create an issue for this immediately
Do I need to create a New one?

**Comment by Ash515** [comment]
No need @simranquirky

**Pull request merged**
