### PR TITLE
created 2 tables(for login and storing)

### LINKED ISSUE #9: Backend: Create tables in the database required the for Project
Database is collection of multiple tables.
We would need minimum need two tables at least -:
1. For login Purpose
2. For storing/updating the scores via admin and student.

Note-: Can be more and you will need to identify the parameters needed in tables.
Feel free to contact if you face any issue

### PR DESCRIPTION
**Pull request by dilroseR**
this pr attempts to close #9

### CODE REVIEW

**Review by abhijeet007rocks8 — CHANGES_REQUESTED** [review]
in login model add a column for usertype having values faculty or student and not null.
Also you can work on Issue #8

**Comment by dilroseR** [comment]
> in login model add a column for usertype having values faculty or student and not null.
> Also you can work on Issue #8

can i create 2 cols one for faculty and one foe student??

**Comment by abhijeet007rocks8** [comment]
> > in login model add a column for usertype having values faculty or student and not null.
> > Also you can work on Issue #8
> 
> can i create 2 cols one for faculty and one foe student??

storing true and false??

**Comment by dilroseR** [comment]
> > > in login model add a column for usertype having values faculty or student and not null.
> > > Also you can work on Issue #8
> > 
> > 
> > can i create 2 cols one for faculty and one foe student??
> 
> storing true and false??

no separate col fields for student and faculty like i did for separate subs

**Comment by abhijeet007rocks8** [comment]
You can add two columns to login table named faculty and student 
and for values you can store true if user id is for student else false similarly for faculty column

**Comment by abhijeet007rocks8** [comment]
@dilroseR why making three table could have just added 2 cols in login table 
Because when a user will enter  he would use his I'd and password but everytime telling that he is faculty is not user friendly
So using the column values of faculty and student we can judge which type of user is logging in

**Comment by dilroseR** [comment]
> @dilroseR why making three table could have just added 2 cols in login table
> Because when a user will enter he would use his I'd and password but everytime telling that he is faculty is not user friendly
> So using the column values of faculty and student we can judge which type of user is logging in

ok ill make 2 cols

**Comment by dilroseR** [comment]
ive updated

**Review by abhijeet007rocks8 — APPROVED** [review]

**Comment by abhijeet007rocks8** [comment]
@fill the form in the slack channel

**Comment by dilroseR** [comment]
what is issue tag id?

**Comment by abhijeet007rocks8** [comment]
> what is issue tag id?

The issue number I'd you resolved in your case I guess it's both 8 and 9

**Comment by dilroseR** [comment]
9 i've resolved
8 is left
i'll make a pr for that as well
is it ok?

**Comment by abhijeet007rocks8** [comment]
Sure

**Pull request merged**
